### ISSUE TITLE
PlayState.hx error

### ISSUE THREAD

**Issue by TheKitBoi** [ninjaninja140/DylanEngine#2]
### Describe your bug here.

fix it plz

### Command Prompt/Terminal logs (if existing)

```bash
source/PlayState.hx:708: characters 56-59 : Expected , or )
```

### Are you modding a build from source or with Lua?

Source

### What is your build target?

Windows

### Did you edit anything in this build? If so, mention or summarize your changes.

no

**Comment by ninjaninja140** [comment]
The engine isnt finished yet, try building from the latest version.
